### PR TITLE
Bump Ktlint to 1.1.1

### PR DESCRIPTION
**Pull request by Goooler**
https://github.com/pinterest/ktlint/releases/tag/1.1.1

Follow up #574.

### CODE REVIEW

**Comment by Goooler** [comment]
Not sure why this update haven't been sent by @dependabot automatically, maybe we can use @renovate-bot to replace it.

**Comment by nilsschmidthamburg** [comment]
The commit itself looks good.
It seems the pipeline failed because some service was temporarly not available.
@see "curl: (22) The requested URL returned error: 503 Service Temporarily Unavailable"

Could somebody with matching rights retrigger the job to see if it will run through now.

We would be very happy to see a version of ktlint-maven-plugin supporting kltint 1.1.1 in the near future. 
Thanks for the great work!

**Comment by freemanjp** [comment]
@Goooler thanks for the PR, sorry for the delay. You can find your fix in version 3.1.1 of this plugin (it may take a few hours for it to be downloadable from Maven Central),

**Comment by Goooler** [comment]
It would be better to follow the latest ktlint version 1.2.1, and draft a new release.

**Comment by Goooler** [comment]
Not sure why @dependabot hasn't sent ktlint updates, maybe we can replace it with @renovate-bot.

**Pull request merged**
